export const REPORT_REPOSITORY_TOKEN = 'REPORT_REPOSITORY_TOKEN';
export const CLASSIFICATION_RESULT_REPOSITORY_TOKEN = 'CLASSIFICATION_RESULT_REPOSITORY_TOKEN';
export const APP_LOGGER_TOKEN = 'APP_LOGGER_TOKEN';
export const AI_CLIENT_TOKEN = 'AI_CLIENT_TOKEN';
export const AI_CACHE_TOKEN = 'AI_CACHE_TOKEN';
export const AI_CLASSIFICATION_SERVICE_TOKEN = 'AI_CLASSIFICATION_SERVICE_TOKEN';
export const CLOCK_TOKEN = 'CLOCK_TOKEN';
export const QUEUE_PRODUCER_TOKEN = 'QUEUE_PRODUCER_TOKEN';
